### ISSUE TITLE
Cant login to SimCam Open Platform

### ISSUE THREAD

**Issue by sushrest** [simshineaicamera/SIMCAM_SDK#4]
Cant login to SimCam Open Platform using correct SimCam App username and password.
Attached Screenshot:
https://platform.simcam.cn/
![screenshot-platform simcam cn-2019 11 27-00_13_18](https://user-images.githubusercontent.com/792249/69636521-e58e1480-10aa-11ea-9550-3771d5fefec0.png)

**Comment by leiqiwen** [comment]
Hi, Can you email us your SimCam account then we can check it. the email is sdk@simcam.ai.

**Comment by sushrest** [comment]
Hi,
Just sent my email address.

**Comment by leiqiwen** [comment]
Hi,the account does't exist in our database, can you login SimCam App with the account?

**Comment by sushrest** [comment]
Yes

**Comment by leiqiwen** [comment]
We found that your account is in China. At present, the account in China cannot support the open platform. You can register for an account in another area.

**Comment by sushrest** [comment]
Thanks I registered another account in another area.. it looks like I was able to login but after entering my username and password i get this:
![screenshot-platform simcam cn-2019 11 27-19_03_47](https://user-images.githubusercontent.com/792249/69704956-ab735000-1148-11ea-9722-3021eaf6bfc5.png)

**Comment by leiqiwen** [comment]
do you get the error when login open platform?can you give us your new account?thank you

**Comment by sushrest** [comment]
@leiqiwen Yes, the error seems to be because authenticated user wasn't being redirected to the main page. I was able to see the dashboard. The new account is the exact same email I sent earlier.

**Comment by leiqiwen** [comment]
Maybe it is caused by the wrong URL address, you can first clear the browser cache and then enter the address https://platform.simcam.cn/    
Try again, thanks.
