### ISSUE TITLE
Docker setup error

### ISSUE THREAD

**Issue by quaesitor-scientiam** [simshineaicamera/SIMCAM_SDK#7]
"Successfully installed mvnc- v1_12.0.1
You are using pip version 8.1.1, however version 20.3.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
NCS Libraries have been installed in /usr/local/lib
NCS Toolkit binaries have been installed in /usr/local/bin
NCS Include files have been installed in /usr/local/include
NCS Python API has been installed in /opt/movidius, and PYTHONPATH environment variable updated
Updating udev rules...
Installation failed. Error on line 630
root@961228f070a0:/SIMCAM_SDK_v1.0.0/tools/mv_toolchain/model_conversion#
"
Is this something that needs to be addressed?

**Comment by RamatovInomjon** [comment]
sudo cp $SDK_DIR/udev/97-usbboot.rules /etc/udev/rules.d/
sudo udevadm control --reload-rules
sudo udevadm trigger


Can you try this?

**Comment by quaesitor-scientiam** [comment]
Well assuming $SDK_DIR is equal to `/SIMCAM_SDK_v1.0.0` then that udev folder does not exist.  Here is the directory at $SDK_DIR:
`root@961228f070a0:/SIMCAM_SDK_v1.0.0# l
README.md  docs/  examples/  img/  libs/  src/  tools/  train/`

Please note all this is from the Docker image describe here https://github.com/simshineaicamera/SIMCAM_SDK It is in step 7 where the error occurred.

**Comment by RamatovInomjon** [comment]
Sorry, it's my bad

**Comment by RamatovInomjon** [comment]
By the way, sudo docker run -ti --name=simcamsdk -v /home/username/:/home/username/ simcam/simcamsdk:v1.0 bash

**Comment by quaesitor-scientiam** [comment]
First command worked.  I then exit the container.
Running from host:
`S:\> docker run -ti --name=simcamsdk -v /home/username/:/home/username/ simcam/simcamsdk:v1.0 bash
docker: Error response from daemon: Conflict. The container name "/simcamsdk" is already in use by container "961228f070a04839471b6fa2e65728ee54c807ec77b0c6af67064b7330399e2f". You have to remove (or rename) that container to be able to reuse that name.`

**Comment by RamatovInomjon** [comment]
Just run 
sudo docker run -ti --name=simcamsdk bash

**Comment by quaesitor-scientiam** [comment]
I got back into my container. 
Successfully ran these two commands:
sudo udevadm control --reload-rules
sudo udevadm trigger

Now to to run the demo.  Alas SimCam sent me an extra camera without a power supply.

Thanks
